# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    container_name: my_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Password
      MYSQL_DATABASE: BookMyEvent
    volumes:
      # - .docker/init.sql:/docker-entrypoint-initdb.d/init.sql
      # - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file: ./.env
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 3000:3000
    command: >
      sh -c "npm run migrate:dev && npm run db:seed"

# volumes:
#   db_data:
